### ISSUE TITLE
Paraview: Error parsing XML in stream / Error parsing input file: ReadXMLInformation aborting

### ISSUE THREAD

**Issue by jvela018** [ElmerCSC/elmer-elmag#23]
Can't post process .vtu results on paraview. 

# Versions:
- Paraview 5.11.2
- Elmer 9.0 (built with MPI and MUMPS)

# Steps to replicate
- Use example: https://github.com/ElmerCSC/elmer-elmag/tree/main/TEAM30a/three_phase
- Run using 
`ElmerSolver harmonic3_with_circuits.sif` 
- Unfortunately this leads to an error coming from the CalcFields solver
![calcfields](https://github.com/user-attachments/assets/bb98223c-c3b8-4d21-a2e9-73bf332d9d8f)
- This can be fixed by adding __Linear System Solver = Direct__ under Solver 3 /Calcfields
- The example will run as expected now
- Open paraview and open the file res/*.vtu and the error Error parsing XML in stream / Error parsing input file: ReadXMLInformation aborting pops up.

![image](https://github.com/user-attachments/assets/a2c48a7b-a7db-44f3-8bec-bd9adadf36d4)

I haven't checked all the examples but a couple of the ones under CircuitBuilder have the same issue. Has anything changed recently where Calcfields requires the linear solver definition and/or where the parsing of data has changed?

Any pointers are appreciated.

/Jon

p.s. @raback

**Comment by jvela018** [comment]
It works with Paraview version 12 and Paraview version 13. 

Closing issue.

**Comment by raback** [comment]
This is probably the reason. Buggy library not related to Elmer.
https://github.com/ElmerCSC/elmerfem/issues/461
