### ISSUE TITLE
Not able to open the MESH on CoilOnIronCore

### ISSUE THREAD

**Issue by nicoceledonc** [ElmerCSC/elmer-elmag#25]
For whatever reason I was able to load the mesh in ElmerGui just **once**.

I got this error always
```
Loading elmer mesh files
Summary:
Nodes: 8871
Point elements: 0
Edge elements: 420
Surface elements: 5404
Volume elements: 46861
Found 8032 edges on boundary
fish: Job 1, 'ElmerGUI' terminated by signal SIGSEGV (Address boundary error)
```

The one time that it worked, it showed the following:
```
Loading elmer mesh files
Summary:
Nodes: 8871
Point elements: 0
Edge elements: 420
Surface elements: 5404
Volume elements: 46861
Found 8032 edges on boundary
Bcs/materials on surface elements: 4
Bcs/materials on edge elements: 1
Bcs/materials on point elements: 0
Generating  lists to display
Generated 11 lists
Ready
```

I installed through macports, and the version it seems to be 
elmerfem @2024.09.21_0+gcc14+openblas (active)

Also tried in windows with version 9.0 but with no success

**Comment by richb2k** [comment]
Running 'ElmerGrid 2 2 MESH -out MESH-out -autoclean', creates a new mesh folder.  The new folder MESH-out loads okay in ElmerGUI in Windows 10 with a compiled date of 3 Dec 2024.  Click on Help, About, to find the ElmerGUI compiled date.
